Danil_Popov_1040/Components/CartViewComponent.cs
using Danil_Popov_1040.Extensions;
using Danil_Popov_1040.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Danil_Popov_1040.Components
{
    public class CartViewComponent : ViewComponent
    {
        private Cart _cart;
        public CartViewComponent(Cart cart)
        {
            _cart = cart;
        }
        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

Danil_Popov_1040/Components/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Danil_Popov_1040.Models;

namespace Danil_Popov_1040.Components
{
    public class MenuViewComponent : ViewComponent
    {
        // Menu list initialization
        private List<MenuItem> _menuItems = new List<MenuItem> {
            new MenuItem{ Controller="Home", Action="Index", Text="Lab 3" },
            new MenuItem{ Controller="Product", Action="Index", Text="Каталог" },
            new MenuItem{ IsPage=true, Area="Admin", Page="/Index", Text="Администрирование" }
        };
        public IViewComponentResult Invoke()
        {
            // Retrieving segment route values
            var controller = ViewContext.RouteData.Values["controller"];
            var page = ViewContext.RouteData.Values["page"];
            var area = ViewContext.RouteData.Values["area"];
            foreach (var item in _menuItems)
            {
                // Controller name checks
                var _matchController = controller?.Equals(item.Controller)
                ?? false;

                // Controller zone checks
                var _matchArea = area?.Equals(item.Area) ?? false;
                // If checks is clear - make menu active
                // CSS class activization
                if (_matchController || _matchArea)
                {
                    item.Active = "active";
                }
            }
            return View(_menuItems);
        }
    }
    }

Danil_Popov_1040/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Danil_Popov_1040</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>


    <header>
        <div class="container">
            <!-- Панель навигации -->
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <!-- меню сайта -->

                <a class="navbar-brand" asp-action="Index" asp-
                   controller="Home">Danil_Popov_1040</a>

                <div class="navbar-nav">
                    @await Component.InvokeAsync("Menu")
                </div>
                <!-- меню сайта - конец -->
                <!-- Информация пользователя -->
                <partial name="_UserPartial" />
                <!-- Информация пользователя - конец -->
            </nav> <!-- Панель навигации - конец -->
            <!-- Панель навигации -->
        </div><!-- container - конец -->
    </header><!-- header - конец -->
    <main class="container">


        @RenderBody()

    </main>
    <footer class="fixed-bottom">
        <div class="container">
            <span class="nav-color">
                <div class="navbar navbar-dark navbar-expand-md bg-dark">
                    <div class="navbar-nav ml-auto">
                        <a class="nav-item nav-link" href="http://www.facebook.com">
                            <i class="fab fa-facebook-f fa-2x"></i>
                        </a>

                        <a class="nav-item nav-link" href="http://www.vk.com">
                            <i class="fab fa-vk fa-2x"></i>
                        </a>
                        <a class="nav-item nav-link" href="http://www.twitter.com">
                            <i class="fab fa-twitter fa-2x"></i>
                        </a>
                    </div>
                </div>
            </span>
        </div>
    </footer>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Danil_Popov_1040/Views/Shared/_UserPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@using Danil_Popov_1040.DAL.Entities;
@inject SignInManager<ApplicationUser> signInManager
@if (signInManager.IsSignedIn(User))
{
    @await Component.InvokeAsync("Cart")


    <div class="dropdown ml-4 nav-color">

        <div class="dropdown-toggle" id="dropdownMenuButton"
             data-toggle="dropdown"
             aria-haspopup="true" aria-expanded="false">
            <img img-action="GetAvatar"
                 img-controller="Image"
                 width="30" alt="User"
                 class="rounded bg-light" />


        </div>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <div class="dropdown-item-text">
                <img img-action="GetAvatar"
                     img-controller="Image"
                     width="30" alt="User"
                     class="rounded bg-light" />
                @User.Identity.Name

                <!--user@mail.ru-->

            </div>
            <div class="dropdown-divider"></div>

            <a class="dropdown-item" asp-controller="Cart" asp-
               action="Index">Мои товары</a>
            <form asp-area="Identity"
                  asp-page="/Account/Logout"
                  asp-route-returnurl="@ViewContext.HttpContext.Request.Path">

                <input type="submit"
                       value="Log off"
                       class="dropdown-item" />

            </form>

            <!--<a class="dropdown-item" asp-area="Identity"-->
            <!--asp-page="/Account/Logout">Log off</a>-->

        </div>
    </div>
}
else
{
    <ul class="nav navbar-nav ml-auto">
        <li>
            <a class="nav-item nav-link"
               asp-area="Identity"
               asp-page="/Account/Login">
                Войти
            </a>
        </li>
        <li>
            <a class="nav-item nav-link"
               asp-area="Identity"
               asp-page="/Account/Register">
                Зарегистрироваться
            </a>
        </li>
    </ul>
}